services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    env_file:
      - ./.env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_CHARACTER_SET=${MARIADB_CHARACTER_SET}
      - MARIADB_COLLATE=${MARIADB_COLLATE}
    volumes:
      - type: bind
        source: /home/ed/md/mariadb_data
        target: /bitnami/mariadb      
      
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '80:8080'
      - '443:8443'
    env_file:
      - ./.env
    restart: always
    environment:
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
    volumes:
      - type: bind
        source: /home/ed/md/moodle_data
        target: /bitnami/moodle
      - type: bind
        source: /home/ed/md/moodledata_data
        target: /bitnami/moodledata
    depends_on:
      - mariadb

